server:
  port: 8081
spring:
  application:
    name: user-com.sesac.userservice.service
  datasource:
    url: jdbc:mysql://localhost:3307/user_service_db


user:
  service:
    name: "User Service"
    version: "1.0"
    description: "사용자 정보를 관리하는 마이크로서비스"